### PR TITLE
swap cheshire for jsonista

### PR DESCRIPTION
**Pull request by domparry**
I had to modify some of the examples due to small differences between cheshire and jsonista, but all tests are passing with these changes.

### CODE REVIEW

**Comment by domparry** [comment]
Yes of course! Great idea. I should have pushed to `devel` in the first place.

**Comment by edporras** [comment]
Mhmm, unfortunately, I'm getting serialization errors. I don't have a lot of time to look but it seems to be caused by setting `key-fn`  to `keyword`. If I add  `json-io` test to add this, it throws :

```clojure
(deftest json-io
  (let [p (ds/make-pipeline [])
        input (ds/read-json-file json-file-path {:name :read-json} p)]
    (-> (PAssert/that input)  (.containsInAnyOrder (map int test-data)))
    (is "read-json" (.getName input))
    (ds/run-pipeline p))
  (testing "with key-fn"
    (let [p (ds/make-pipeline [])
          input (ds/read-json-file json-file-path {:name :read-json-k :key-fn keyword} p)]
      (-> (PAssert/that input)  (.containsInAnyOrder (map int test-data)))
      (is "read-json-k" (.getName input))
      (ds/run-pipeline p))))
```

Any ideas?

**Comment by domparry** [comment]
I'll take a look here quickly.

**Comment by domparry** [comment]
I will look again tomorrow, but the actual class that's causing issues is `Caused by: java.io.NotSerializableException: java.time.format.DateTimeFormatter`. I know that jsonista allows you to pass in a date formatter, but the test data doesn't contain any dates...

**Comment by edporras** [comment]
Yeah, I thought that was curious too because the pipeline I tested with does not have dates in the data either so it must be something to do with how Beam manages things on the Java side. Perhaps @ngrunwald has some insight.

**Comment by domparry** [comment]
I'm going to work on it today a bit. I'll also test with https://cnuernber.github.io/dtype-next/tech.v3.datatype.char-input.html#var-read-json and see if that gives the same issue.


Kind Regards,
Dom Parry
0828236887

**Comment by domparry** [comment]
I have solved this. the fix is over here: https://github.com/ngrunwald/datasplash/pull/112

**Comment by domparry** [comment]
@edporras : Before you merge into master, I'm experimenting with removing the dependency on jackson. I think this is a benefit for a beam library as it means uploading less into the pipeline payload, which allows more space for other things. I'll be doing some work on it today, and will let you know how it goes. I'm looking at using https://github.com/cnuernber/charred, which has now been extracted from dtype-next, and include parsing back to json strings which was missing last week.

**Comment by edporras** [comment]
I merged and released over the weekend 😅

**Comment by domparry** [comment]
Ah. Sorry. I didn't even check. I'll continue anyway and let you know how it goes.

**Comment by edporras** [comment]
No problem. Sorry, been pretty busy and had some time to do it so didn't want to leave it on the back burner.

I've been wanting to improve the tests and also to look at the issue with generate-input serializing of Boolean values. I'll see if I can tackle at least one while you work on that.

Thanks again.

**Comment by edporras** [comment]
Well, tried running a few more pipelines with the latest version and it's causing me problems. Some of the pipelines are not completing 😞. Let me know when you have something ready and I'll give it a try. Thanks.

**Comment by domparry** [comment]
Oh dear. Sorry to hear that. Which IO's are you using in those pipelines? I'm using it with Bigquery sink, datastore source and sink, pubsub source and sink an they are working well for me. I released a new version on my fork with charred last night which is also working well. I haven't run any ES workloads yet as we don't have any.

**Comment by RolT** [comment]
I was using jsonista in place of cheshire for a while for text IO and the only problem I ever encountered was setting the object mapper correctly for dates in jsonista (cheshire does this by default)

**Pull request merged**
