### PR TITLE
Adding support for standard sql syntax for BigQuery queries

### PR DESCRIPTION
**Pull request by torbjornvatn**
This PR also bumps the google-cloud-dataflow-java-sdk-all to 1.9.0

### CODE REVIEW

**Comment by ngrunwald** [comment]
merged but changed the option to :standard-sql? to be more conformant with the rest of the lib

**Comment by torbjornvatn** [comment]
Cool, that makes sense

**Comment by torbjornvatn** [comment]
Do you have a new release in the pipes by the way?

**Comment by ngrunwald** [comment]
v0.4.1 is released and pushed to clojars

**Comment by domparry** [comment]
I see the docs point to 0.4.2-snapshot. Is that intentional?

**Pull request closed without merging**
