### PR TITLE
Add Set distinct operations for PCollections

### PR DESCRIPTION
**Pull request by FiV0**
This adds three new `set` operations to the API. `intersect-distinct`, `union-distinct` and `except-distinct`.

### CODE REVIEW

**Comment by edporras** [comment]
@FiV0 this is great! Could you rebase it to `devel` instead of master? I'll merge, then push a release.

**Comment by FiV0** [comment]
Done. Maybe you could also bump `charred` to the latest version as we have some issues with json-decoding on our pipeline. Trying to go from `7.4` to `7.12` also changes json serialisation from `cheshire` to `charred`.

**Comment by edporras** [comment]
What JSON problems are you having? The last two releases include commits to improve EOF handling so do you think that would help? We did a couple of MRs to Chris regarding encoding / decoding issues and incompatibility with charred and got them resolved pretty quickly. We should create the issues there and then do a datasplash release afterward.

**Comment by FiV0** [comment]
Yes, I am getting `Caused by: java.io.EOFException: Unexpected end of input`. The only way I could get this locally is with an empty line in one of the inputs. I ran `charred` on the whole input that caused this (concatenated) and it didn't produce it locally.

**Comment by edporras** [comment]
Sounds good!

**Pull request merged**
