### PR TITLE
Handle RECORD type in BigQuery schemas

### PR DESCRIPTION
**Pull request by torbjornvatn**
I hit an issue with a BigQuery schema containing a RECORD type.
The existing `->schema` function doesn't handle this, so I had to add som recursion.
I also wrote a test specifically for this change.

### CODE REVIEW

**Comment by torbjornvatn** [comment]
@m-lce @ngrunwald I found a limitation in the current `->schema` function when working with nested schemas

**Comment by domparry** [comment]
So this looks amazing. Particularly the nested Schema solution. Do you think this would neatly handle multiple nested levels? For example (Purely made up, but I have a deeply nested structure like this):

```
patient-Record:
   :fields
      :name
      :surname
      :visit-record
         :fields
            :date
            :doctor
            :diagnosis-record
               :fields
                  :diagnosis-code
                  :diagnosis-description
```

**Comment by domparry** [comment]
@torbjornvatn Just a note that I ran into compliation issues when I switched to your clojars release:

`[org.clojars.unacast/datasplash "0.4.2-unacast"]`

This code runs fine on `[datasplash "0.4.0"]`

Stacktrace below:

```
Feb 23, 2017 1:54:50 PM com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner fromOptions
INFO: PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 88 files. Enable logging at DEBUG level to see which files will be staged.
Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/mc/6vrbpxbs60q4hwdrp8wm89380000gn/T/form-init8815651323456616385.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at clojure.core$name.invokeStatic(core.clj:1546)
	at clojure.core$name.invoke(core.clj:1540)
	at datasplash.bq$clean_name.invokeStatic(bq.clj:72)
	at datasplash.bq$clean_name.invoke(bq.clj:67)
	at datasplash.bq$clj__GT_TableFieldSchema$iter__6339__6343$fn__6344$fn__6345.invoke(bq.clj:131)
	at datasplash.bq$clj__GT_TableFieldSchema$iter__6339__6343$fn__6344.invoke(bq.clj:129)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:144)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:145)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:145)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:106)
	at com.google.api.client.json.JsonFactory.toByteStream(JsonFactory.java:171)
	at com.google.api.client.json.JsonFactory.toString(JsonFactory.java:154)
	at com.google.api.client.json.JsonFactory.toString(JsonFactory.java:112)
	at com.google.cloud.dataflow.sdk.io.BigQueryIO.toJsonString(BigQueryIO.java:3032)
	at com.google.cloud.dataflow.sdk.io.BigQueryIO$Write$Bound.withSchema(BigQueryIO.java:1846)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at datasplash.bq$fn__6365.invokeStatic(bq.clj:168)
	at datasplash.bq$fn__6365.invoke(bq.clj:168)
	at datasplash.core$with_opts$fn__5260.invoke(core.clj:379)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$reduce.invoke(core.clj:6527)
	at datasplash.core$with_opts.invokeStatic(core.clj:375)
	at datasplash.core$with_opts.invoke(core.clj:373)
	at datasplash.core$apply_transform.invokeStatic(core.clj:419)
	at datasplash.core$apply_transform.invoke(core.clj:413)
	at datasplash.bq$write_bq_table_raw.invokeStatic(bq.clj:187)
	at datasplash.bq$write_bq_table_raw.invoke(bq.clj:184)
	at datasplash.bq$write_bq_table_clj_transform$fn__6374.invoke(bq.clj:202)
	at datasplash.bq.proxy$com.google.cloud.dataflow.sdk.transforms.PTransform$ff19274a.apply(Unknown Source)
	at com.google.cloud.dataflow.sdk.runners.PipelineRunner.apply(PipelineRunner.java:75)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.apply(DataflowPipelineRunner.java:474)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:368)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:291)
	at com.google.cloud.dataflow.sdk.values.PCollection.apply(PCollection.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at datasplash.core$tapply.invokeStatic(core.clj:401)
	at datasplash.core$tapply.invoke(core.clj:398)
	at datasplash.core$apply_transform.invokeStatic(core.clj:420)
	at datasplash.core$apply_transform.invoke(core.clj:413)
	at datasplash.bq$write_bq_table.invokeStatic(bq.clj:207)
	at datasplash.bq$write_bq_table.invoke(bq.clj:204)
	at fulliautomatix.core$apply_transformations_to_pipeline.invokeStatic(core.clj:168)
	at fulliautomatix.core$apply_transformations_to_pipeline.invoke(core.clj:155)
	at fulliautomatix.core$_main.invokeStatic(core.clj:181)
	at fulliautomatix.core$_main.doInvoke(core.clj:170)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init8815651323456616385.clj:1)
	at user$eval5.invoke(form-init8815651323456616385.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

**Comment by torbjornvatn** [comment]
@domparry I do believe it should work for multiple nested levels although I haven't tested it.
Regarding the NPE it seems like one of the maps at some level in your schema doesn't have a `:name` key-value pair. The `clj->TableFieldSchema` functions should probably have had some kind of validation for the keys it relies on.

**Comment by domparry** [comment]
You are 100% correct.. I found this after many hours of searching. Thank you!

**Comment by torbjornvatn** [comment]
Included in #10 so I close this

**Pull request closed without merging**
