### PR TITLE
feature: Add delete-datastore-raw to datastore features

### PR DESCRIPTION
**Pull request by domparry**
I have tested this and it works. It's a simple addition, but hopefully it helps someone else.

### CODE REVIEW

**Comment by RolT** [comment]
Thanks for the PR.
I do have a small preference for using `deleteKey` instead of `deleteEntity` method as the default "raw" delete. Other than that I approve the PR, we can always add `deleteKey` later making `deleteEntity` the default option.

**Comment by domparry** [comment]
You make a good point! deleteKey for "raw" does make more sense. I'll test that first, and resubmit.

**Comment by RolT** [comment]
Can someone merge this please ?

**Comment by bfontaine** [comment]
I reverted the commit because it got merged in master ; I added it in devel instead: https://github.com/ngrunwald/datasplash/commit/fe3ea2093cdbd80f425935de98aff2f027538005

**Pull request merged**
