### PR TITLE
Upgrade Apache Beam SDK to 2.10.0 & CircleCI

### PR DESCRIPTION
**Pull request by xingxing**

### CODE REVIEW

**Comment by bfontaine** [comment]
Hello :wave: 
Sorry for the late response; could you please remove the `circle CI` commit so we have only the Apache Beam bump in that PR? We don’t use Circle CI, but you can try to convince @ngrunwald to do so. :slightly_smiling_face:

Thanks!

**Comment by xingxing** [comment]
@ngrunwald, @bfontaine 
Hey, guys.  I've removed the CircleCI commit. And I still think add a CI to run unit test (event release automatically) is good practice, thus contributors should had more confidence for every changes.

**Comment by bfontaine** [comment]
I agree! cc @ngrunwald :wink:

**Comment by bfontaine** [comment]
Merged in https://github.com/ngrunwald/datasplash/commit/d4466e80d4a0cb28c1d866ef1830bbab8bc095a1. Thank you! :tada:

**Pull request closed without merging**
