### PR TITLE
test: another pass at improving tests

### PR DESCRIPTION
**Pull request by edporras**
* added more missing tests
* generate fixtures on demand

### CODE REVIEW

**Comment by edporras** [comment]
@domparry : https://github.com/cnuernber/charred/issues/4 
We produce large amounts of JSON output using ds so we have to add this option on the write-json functions

**Comment by domparry** [comment]
I think that's a sensible option to add, because it feels like unformatted should be the default. It might be worth looking into write-json-fn, since we can set this up once as a common function that can then be used all over the lib. The reason is that it Chris mentioned that one of the things that you pay performance penalty for is parsing of the options each time you call the write functions. I'll look into this and change the MR if you agree.

**Comment by edporras** [comment]
Sounds good. I also found odd that unformatted was not the default since it's supposed to be a drop-in replacement 🤷‍♂️.

Thanks!

**Comment by cnuernber** [comment]
It is supposed to be a drop-in replacement - I was under the impression that clojure.data.json wrote readable json but I was wrong.  1.007 fixes both the issue that indent-str didn't completely remove whitespace and that writing pretty-printed json was the default :-).

**Comment by domparry** [comment]
Much appreciated Chris! We love Charred. Thanks so much for the effort. @edporras , I have pushed the updates to the cheshire->charred branch PR (https://github.com/ngrunwald/datasplash/pull/120)

**Pull request merged**
