### PR TITLE
Version v0.7.8, complete dofn lifecycle

### PR DESCRIPTION
**Pull request by xfthhxk**
Hi. I took the liberty of adding calls for `start-bundle`, `finish-bundle` and `teardown` to complete the `DoFn` lifecycle calls.  My pipeline requires batching calls to other services and closing resources.  Let me know if you'd like any changes.  Thanks!

### CODE REVIEW

**Comment by edporras** [comment]
Hi Amar, thank you for the MR. I've got a few more test changes I'm going to push to `devel` and will merge yours to do a release including both.

**Comment by edporras** [comment]
@xfthhxk sorry, I think I really messed something up by mistake. I'm tired and probably shouldn't be doing this right now 😅

I don't know how I managed to do this but it looks like I merged the branch here onto yours? I can't seem to figure out how to get your branch now. Could you re-push yours again without my attempt to rebase?

**Comment by edporras** [comment]
@xfthhxk never mind.. I see what happened. Sorry about that.

**Comment by edporras** [comment]
merged to `devel`

**Comment by xfthhxk** [comment]
Hi @edporras I think there's some issue with the merge.  I'm not seeing the DoFn lifecycle changes in `devel`.  Created a new PR #121

**Pull request closed without merging**
